config/routes.rb
Rails.application.routes.draw do
  get 'answer', to: 'coaching#answer'
  get 'ask', to: 'coaching#ask'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def answer
    @query = params[:query]
    if @query == "I am going to work right now!"
      @answer = ""
    elsif @query.include?("?")
      @answer =  "Silly question, get dressed and go to work!"
    else
      @answer =  "I don't care, get dressed and go to work!"
    end
  end

  def ask
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<h1>Coaching#answer</h1>

<%= @answer %><br>

<%= link_to "Ask a new question!", ask_path %>

app/views/coaching/ask.html.erb
<h1>Coaching#ask</h1></br></br>
<center>
<form action="/answer">
  <label for="question">Speak to your coach</label></br></br>
  <input type="text" id="question" name="query" placeholder="what time is it?"></br></br>
  <input type="submit" value="Go on!" class="btn btn-primary"></br></br>
</form>

</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stupidcoaching</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>